version: "3"
services:
  app:
      build: ./docker/php
      container_name: app
      volumes:
        - ./docker/php/php.ini:/usr/local/etc/docker/php/php.ini
        - ./html:/var/www/html
        - .:/var/www
      ports:
        - 8080:80
      depends_on:
        - db

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    platform: linux/amd64
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - TZ='Asia/Tokyo'
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=db-user
      - MYSQL_PASSWORD=db-pass
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    links:
      - db
    ports:
      - 8001:80
    volumes:
      - /sessions
